language: node_js
node_js:
- '0.12'
- '4.0'
- '4.1'
cache:
  directories:
  - node_modules
notifications:
  secure: fR96PteJRUCv7cNwvKP5oF6TDpSdfYg16njuR0vILFzvaeZUFreemIWS1sf3lQMZXnFK9L26DHPoXhWm9tyaDWeLUWPdT60xJ350qXX24pTgcIyYvvgm+vhaYNsFyLm+Fh/Q+l37U1lBw6O/inlpN9YcGqmcJMpydi8nESX2f/N8WSbDfWqmFd3F+uMeKbuG74BB4p8QmZenYx1vFRV2jR35VDs1sUe7ZHBrM7Bb9BUEW0DAtWIkGDhwihs1KjajY+YjDUgri6001Ka65LSlnUNQUH9aJ7YdMnWRhmVjWTVUmfHlA1SxkkexZN4mbYJCbjUQCKG4cAds3di8O2M0EBMFrZJU4MdGW6QvKpeHf21SBfk0tm7Wzm2jxawBFyXUTQcjSzSJ2PGlkv5hQlY99wnpBlXepKKkc9dfbD6JQbzUs3yKW0oGNmg6FCwR8OhrKgYsLz/JqeA014YnZEWXlYJJOxaB9NLtOfNu16WKh4ZLxhIz49QizQ2YBW0B8A1/1C8alI88PPsjDsZOOZ1DBK4d9mudPPk17bfsrAUI5G55xsxQjsu8jSb2Wq246gBZxH5tNrqJLHaQVvvKfOAHC82YnDmTfg54Jmil0c/CTumTLLh0LuOztIwqc6Y1iT5XL+x6MrNLccXEP9cYI64pVFnI58/wwjb36ITYdqrg18Y=
  slack:
    secure: WA8UfLL25x/wWqDUIhSnygpRpmCvBgi6MaOEPBNcHj1KZBpE2fm6IIhINSdWoikAr20Pa1X0hCXEuvM61EDIZoPlx1J97bBkro2LpMJ7AAvyLRPz6syprN2rX7bwiuS0bQhCAiH4gXs2Q3l8W5+O+QSWu0Koi8puI16r0i8aXItsIHrz7ZBCjHnWsWa4f0CmstNt1F8K9vC2sg8DRkD8Q88YOBZjyAH7FQs4dbZyExVHAtOIjhqEcL+vXfEbPtZxCcHzSYZzdPT43XMucS0WUVtFqrnghYtbPGc+KVHQx1Q/GGjnazfTdFCLxsvwU9C5Kfp3uX3c37JuHM1PRhI9Y28RyGyP9vKOwosiSn+p7fM7u8H1z49mc7oaBCLFV50zfCggh3seKmvUYNuLAmfiVgm1DDsTEGe83zFHq3CFb0P9L1aIevgw3gNutWgHqOGjj/L9ADyGG+L9yM+4WKrZzSA/AkQmsCJCN4ArdxGzTrnDIr5+XZaDEC1nBTxmbcIcaf0+L7fG8rWfMzfs4W0q9XVGNxhzRdU5ql5E5NsJ9kVDM/1pUllbuEsE4Usa8x29V7VBAFNHXjwEllduj4jtW+OkDZ9Zre+M4+f626jCl108W6at1+RQfiwXaz9t8jtRS5pLe+B1g9zHYMjzNoMUXTow6NMwPPM7p6zCtooBOwI=
